# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI Test

on:
  push:
    branches:
      - 'develop'
      - 'feature/*'
  pull_request:
    branches:
      - 'develop'
      - 'feature/*'

jobs:
  CI-Local-Test:
    ## Naver Dev-Server OS : ubuntu-18.04
    runs-on: ubuntu-18.04

    steps:
      ## JDK Setting
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      ## Main Branch Make yml
      - name: make application-prod.properties
        if: contains(github.ref, 'develop')
        run: |
          cd ./src/main/resources
          sed -i'' -e  's/riot-api-key/${{ secrets.APIKEY }}/g' constants.yml 
          rm  constants.yml.bak
          cat constants.yml
        shell: bash

      ## Gradle
      - name: Grant Execute permission for gradlew
        run: |
          pwd
          chmod +x gradlew

        shell: bash

      - name: Build with Gradle
        run: ./gradlew build -x test
        shell: bash

      - name: Test with Gradle
        run: SPRING_PROFILES_ACTIVE=[local] ./gradlew clean test
        shell: bash

      - name: Publish Unit Test Test Result
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          files: build/test-results/**/*.xml
